"""Generate LLM-authored adversarial preference MCQs.

This file implements a LoCoMo-style adversarial QA layer for the existing
preference benchmark.  Unlike ordinary refusal QA, every question has a real
lure answer backed by memory clues, but the question deliberately mutates one
critical slot in the premise.  The correct answer is therefore the refusal
option, while ``adversarial_answer`` stores the tempting but unsupported answer.

The script uses the deterministic pipeline only to choose the lure answer,
valid memory clues, options, and target adversarial type.  The adversarial
question, trap explanation, and reasonable answer are generated by an LLM with
type-specific good cases in the prompt.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import re
import threading
from pathlib import Path

from json_repair import repair_json
from scripts.common.io import load_json_or_jsonl as load_records
from scripts.common.llm import env_value, message_content_to_text, openai_client, usage_value
from scripts.qa.config import profile_path, qa_path

PROFILE_PATH = profile_path("profiles_with_anchors.jsonl")
FORMATTED_DIALOG_PATH = qa_path("qa_formatted_data_000_019.json")
PREFERENCE_QA_PATH = qa_path("qa_preference_mcq.json")
OUTPUT_PATH = qa_path("qa_adversarial_llm_mcq.json")

MODEL = env_value("CUE_MEM_LLM_MODEL", "deepseek-v4-pro")
LLM_RETRIES = 2
TEMPERATURE_GEN = 0.7

CATEGORIES = [
    "FoodAndDrink",
    "HomeAndSpace",
    "BodyAndHealth",
    "HobbiesAndEntertainment",
    "WorkAndLearning",
    "MobilityAndTravel",
    "Pets",
]

OPTION_LABELS = ["A", "B", "C", "D"]
REFUSAL_TEXT = "历史中没有说明"
QAS_PER_PREF = 3
DEFAULT_WORKERS = 8

ADVERSARIAL_TYPES = [
    "person_owner_swap",
    "attribute_slot_swap",
    "category_type_swap",
    "lexical_concept_swap",
    "polarity_flip",
    "false_presupposition",
    "event_context_swap",
    "implicit_overclaim",
]


def parse_profile_ids(value: str | None) -> set[int] | None:
    """Parse comma/space separated profile ids from CLI."""
    if not value:
        return None
    ids: set[int] = set()
    for part in re.split(r"[\s,]+", value.strip()):
        if not part:
            continue
        try:
            ids.add(int(part))
        except ValueError as exc:
            raise argparse.ArgumentTypeError(
                f"--only_profile_ids contains a non-integer value: {part!r}"
            ) from exc
    return ids

GOOD_CASES = {
    "person_owner_swap": {
        "adversarial_type": "person_owner_swap",
        "Q": "苏雨桐挑餐馆时最看重什么样的空间风格？",
        "options": {"A": "新开且有设计感的小馆子", "B": "历史中没有说明", "C": "装修华丽的大餐厅", "D": "连锁品牌标准化门店"},
        "A": "B",
        "adversarial_answer": "新开且有设计感的小馆子",
        "trap_reason": "真实偏好属于林晓澜，不是苏雨桐；题干把偏好归属错配到 relationship 人物身上。",
        "reasonable_answer": "历史中没有说明苏雨桐挑餐馆时最看重什么；只知道林晓澜偏爱新开且有设计感的小馆子。",
    },
    "attribute_slot_swap": {
        "adversarial_type": "attribute_slot_swap",
        "Q": "林晓澜家里那只狗给她带来了什么样的陪伴感？",
        "options": {"A": "像家人一样的重要生活陪伴", "B": "帮她看家护院的安全感", "C": "历史中没有说明", "D": "每天出门遛弯的运动伙伴"},
        "A": "C",
        "adversarial_answer": "像家人一样的重要生活陪伴",
        "trap_reason": "真实信息是她养猫，不是狗；题干把对象属性从猫改成狗。",
        "reasonable_answer": "历史中没有说明她养狗；她提到的是猫带来的陪伴感。",
    },
    "category_type_swap": {
        "adversarial_type": "category_type_swap",
        "Q": "林晓澜特别喜欢看哪类悬疑剧？",
        "options": {"A": "关于建筑、艺术家或创意产业的", "B": "关于连环罪案的硬核推理", "C": "历史中没有说明", "D": "关于家庭伦理悬疑的"},
        "A": "C",
        "adversarial_answer": "关于建筑、艺术家或创意产业的",
        "trap_reason": "真实偏好是纪录片题材，不是悬疑剧；题干把内容类别换错。adversarial_answer 沿用了原偏好的内容方向，在悬疑剧语境下仍然具有迷惑性。",
        "reasonable_answer": "历史中没有说明她特别喜欢哪类悬疑剧；她偏爱的是建筑、艺术家或创意产业相关纪录片。",
    },
    "lexical_concept_swap": {
        "adversarial_type": "lexical_concept_swap",
        "Q": "林晓澜最近迷上的那种网红打卡餐厅是什么风格？",
        "options": {"A": "新开且有设计感的小馆子", "B": "历史中没有说明", "C": "社交平台高分网红店", "D": "明星同款拍照餐厅"},
        "A": "B",
        "adversarial_answer": "新开且有设计感的小馆子",
        "trap_reason": "原偏好是有设计感的小馆子，题干把它恶意改写成网红打卡餐厅。",
        "reasonable_answer": "历史中没有说她迷上网红打卡餐厅；相反，她偏好有完整设计逻辑的小馆子。",
    },
    "polarity_flip": {
        "adversarial_type": "polarity_flip",
        "Q": "林晓澜最不喜欢哪类旅行目的地？",
        "options": {"A": "有强烈在地设计文化的城市", "B": "商业化过度的旅游景区", "C": "历史中没有说明", "D": "偏远无特色的小城镇"},
        "A": "C",
        "adversarial_answer": "有强烈在地设计文化的城市",
        "trap_reason": "真实信息是她喜欢这类城市，题干把 favorite 改成 least favorite。",
        "reasonable_answer": "历史中没有说明她最不喜欢哪类目的地；她反而偏好有强烈在地设计文化的城市。",
    },
    "false_presupposition": {
        "adversarial_type": "false_presupposition",
        "Q": "林晓澜第一次开个人设计展时，哪本设计年鉴给了她最大启发？",
        "options": {"A": "《2025日本平面设计年鉴》", "B": "《国际建筑年鉴》", "C": "《当代艺术评论合集》", "D": "历史中没有说明"},
        "A": "D",
        "adversarial_answer": "《2025日本平面设计年鉴》",
        "trap_reason": "历史只说她收藏设计年鉴，没有说她开过个人设计展，也没有说这本书给展览启发。",
        "reasonable_answer": "历史中没有可靠信息支持这个说法。",
    },
    "event_context_swap": {
        "adversarial_type": "event_context_swap",
        "Q": "林晓澜和拿铁互动时，提到家里最重要的收藏角落是什么？",
        "options": {"A": "设计类书籍和画册所在的书架", "B": "历史中没有说明", "C": "宠物玩具和猫爬架的区域", "D": "旅行纪念品的展示柜"},
        "A": "B",
        "adversarial_answer": "设计类书籍和画册所在的书架",
        "trap_reason": "书架收藏来自另一个话题；拿铁互动事件主要体现宠物陪伴。",
        "reasonable_answer": "她和拿铁互动时没有提到家里最重要的收藏角落。",
    },
    "implicit_overclaim": {
        "adversarial_type": "implicit_overclaim",
        "Q": "林晓澜为什么说自己每天开工前一定要先煮咖啡？",
        "options": {"A": "为了营造工作前的仪式感", "B": "历史中没有说明", "C": "需要咖啡因提神开工", "D": "为了消化早餐再开始工作"},
        "A": "B",
        "adversarial_answer": "为了营造工作前的仪式感",
        "trap_reason": "咖啡习惯来自背景音推断；历史中没有她明确解释原因，也没有说“一定每天”。adversarial_answer 从行为描述适配为符合题干问法的动机表述，保留了仪式感这一核心语义。",
        "reasonable_answer": "历史中没有说明她为什么这样做；只能从背景音推测她有在家准备咖啡的习惯。",
    },
}

PROMPT_GEN_ADVERSARIAL = """你要为一个记忆问答 benchmark 生成 LoCoMo 风格的 adversarial question。

核心任务：
- 已知一个真实偏好事实和真实诱饵答案 adversarial_answer。
- 你必须构造一个自然中文问题，让它看起来像普通记忆问答，但题干中有一个错误前提。
- 错误前提必须属于指定 adversarial_type。
- 正确回答应当拒绝错误前提或纠正它，而不是直接回答 adversarial_answer。

绝对要求：
1. 只生成指定 adversarial_type：{target_type}
2. Q 必须是自然问题，不要出现"这段记录中""根据某段记录""回想某次分享"、日期、session id、memory clue id。
3. Q 中必须只篡改一个关键槽位，不要同时错配多个槽位。
4. 你必须同时生成 4 个选项 options（A/B/C/D），约束如下：
   a. 必须恰好有一个选项内容为“历史中没有说明”，这是唯一正确答案。
   b. adversarial_answer 必须作为另一个选项出现，它是诱饵选项。
      - 如果 target_type 不改变问题主题域（person_owner_swap / polarity_flip / lexical_concept_swap / false_presupposition / event_context_swap），直接使用给定的诱饵答案原文。
      - 如果 target_type 改变了问题主题域（category_type_swap / attribute_slot_swap / implicit_overclaim），必须在保留核心语义特征的前提下适配新主题的措辞和问法，使 adversarial_answer 在新题干下看起来是一个合理且有迷惑性的回答。例如：原偏好是“常把现成饭菜微波一下”，题干问“整理书架的习惯”，adversarial_answer 可改写为“常把常翻的书随手堆在桌边”（保留了“随性便捷”的语义内核）。
   c. 另外两个选项必须是与篡改后题干主题自然匹配的合理干扰项。
   d. 每个选项应简洁（5-20字），不要写完整句子。
   e. Q 的提问方式必须与选项的回答形式搭配：如果 Q 问“为什么”，选项应该是原因；如果 Q 问“哪一项/哪种”，选项应该是事物描述；如果 Q 问“偏好什么”，选项应该是偏好内容。
5. 如果 target_type 是 person_owner_swap，错配对象只能来自 Relationship 候选，不能换成另一个 benchmark character。
6. 如果 expression_type 是 implicit，尤其适合 implicit_overclaim：不要把背景音/图像边缘推断伪装成用户明说。
7. 输出必须是严格 JSON 对象，不要 markdown，不要额外说明。

迷惑性要求：
- adversarial_answer 的核心迷惑力在于：模型在记忆中确实有相关信息，容易错误匹配到这个选项。
- 对于改变主题域的类型，适配后的 adversarial_answer 必须保留原始偏好的核心语义特征（如"随性""偏爱小众""注重氛围""讲究仪式感"等），让模型容易把记忆中的真实偏好联想到这个选项上。
- 两个干扰选项不应来自真实记忆，应该是同主题域的合理猜测。

当前类型 good case：
{good_case}

类型解释：
- person_owner_swap：真实偏好属于用户，但题干问成 relationship 人物的偏好。
- attribute_slot_swap：真实对象存在，但题干把对象/属性槽位改错，如猫改成狗。
- category_type_swap：真实偏好属于 A 类，题干问成 B 类。
- lexical_concept_swap：把中性概念恶意改写成另一个带偏差的概念，如 forum 改 cult。
- polarity_flip：把喜欢/支持改成不喜欢/反对。
- false_presupposition：题干强行假设一个历史中不存在的事件前提。
- event_context_swap：真实答案来自一个语境，题干塞进另一个语境。
- implicit_overclaim：隐式线索能推断，但题干问成“用户明确说过/解释过/每天一定”。

输入信息：
用户姓名: {true_name}
Relationship 候选: {relationship_candidates}
目标错配 relationship 人物: {relationship_wrong_name}
偏好类别: {category}
偏好子类: {subcategory}
偏好描述: {preference}
表达类型: {expression_type}
证据来源: {evidence_sources}
分析依据: {analysis}
普通 preference 问题: {base_question}
诱饵答案 adversarial_answer: {adversarial_answer}
普通题干选项: {base_options}
相关真实证据摘要:
{evidence_summary}
可用于 event_context_swap 的不匹配语境: {wrong_context}

输出格式：
{{
  "adversarial_type": "{target_type}",
  "Q": "自然中文问题",
  "options": {{"A": "选项A", "B": "选项B", "C": "选项C", "D": "选项D"}},
  "A": "正确答案字母（历史中没有说明对应的字母）",
  "adversarial_answer": "诱饵答案文本（必须与 options 中某个选项内容完全一致）",
  "trap_reason": "说明题干改错了哪个槽位，以及为什么 adversarial_answer 只是诱饵",
  "reasonable_answer": "更合理的回答，应该拒绝错误前提或纠正它"
}}
"""


def load_json_or_jsonl(path: Path) -> list:
    if not path.exists():
        return []
    return load_records(path)


def call_llm(prompt: str, temperature: float = TEMPERATURE_GEN) -> tuple[dict, int, int]:
    client = openai_client(
        api_key_env="CUE_MEM_LLM_API_KEY",
        base_url_env="CUE_MEM_LLM_BASE_URL",
        timeout=60.0,
    )
    last_err = None
    last_text = ""

    for _ in range(LLM_RETRIES):
        try:
            api_res = client.chat.completions.create(
                model=MODEL,
                messages=[{"role": "user", "content": prompt}],
                temperature=temperature,
                stream=True,
                stream_options={"include_usage": True},
            )
            text = ""
            usage_info = None
            for chunk in api_res:
                if chunk.choices:
                    text += message_content_to_text(chunk.choices[0].delta.content)
                if hasattr(chunk, "usage") and chunk.usage is not None:
                    usage_info = chunk.usage

            last_text = text
            cleaned = text.strip().replace("```json", "").replace("```", "").strip()
            data = json.loads(repair_json(cleaned))
            tokens_in = usage_value(usage_info, "prompt_tokens")
            tokens_out = usage_value(usage_info, "completion_tokens")
            return data, tokens_in, tokens_out
        except Exception as exc:
            last_err = exc
            print(f"[call_llm] Error: {exc}; raw_tail={last_text[-200:]}")

    raise RuntimeError(f"call_llm failed after {LLM_RETRIES} attempts: {last_err}")


def profile_name(profile: dict) -> str:
    basic = profile.get("Basic") or {}
    return str(basic.get("name") or profile.get("name") or f"用户{profile.get('id', '')}")


def relationship_names(profile: dict) -> list[str]:
    basic = profile.get("Basic") or {}
    relationships = basic.get("Relationship") or []
    names = []
    for rel in relationships:
        name = str(rel.get("name", "")).strip()
        if name and name not in names:
            names.append(name)
    return names


def preference_items(profile: dict) -> list[dict]:
    out = []
    p_id = int(profile.get("id", len(out)))
    for category in CATEGORIES:
        prefs = profile.get(category) or []
        for idx, pref in enumerate(prefs):
            out.append(
                {
                    "p_id": p_id,
                    "category": category,
                    "pref_idx": idx,
                    "pref_code": f"{category}-{idx}",
                    "subcategory": pref.get("subcategory", ""),
                    "preference": pref.get("preference", ""),
                    "expression_type": pref.get("expression_type", ""),
                    "evidence_sources": pref.get("evidence_sources", []),
                    "analysis": pref.get("analysis", []),
                }
            )
    return out


def collect_preference_events(formatted_profile: dict, pref_code: str) -> list[dict]:
    events = []
    for event in formatted_profile.get("events", []) or []:
        codes = []
        codes.extend(event.get("explicit_preferences_reflected", []) or [])
        codes.extend(event.get("implicit_preferences_reflected", []) or [])
        if pref_code in codes:
            events.append(event)
    return events


def collect_valid_clue_keys(events: list[dict]) -> set[str]:
    valid = set()
    for event in events:
        for turn in event.get("dialog_list", []) or []:
            round_id = turn.get("round")
            if isinstance(round_id, str) and round_id:
                valid.add(round_id)
            for key in turn:
                if key.endswith(".png") or key.endswith(".wav"):
                    valid.add(key)
    return valid


def fallback_clues(events: list[dict], expression_type: str) -> list[str]:
    clues = []
    for event in events:
        for turn in event.get("dialog_list", []) or []:
            if expression_type == "implicit":
                for key in turn:
                    if key.endswith(".wav") or key.endswith(".png"):
                        clues.append(key)
            else:
                round_id = turn.get("round")
                if round_id:
                    clues.append(round_id)
                for key in turn:
                    if key.endswith(".png"):
                        clues.append(key)
            if len(clues) >= 3:
                return dedupe(clues)
    return dedupe(clues)


def dedupe(values: list[str]) -> list[str]:
    out = []
    for value in values:
        if value and value not in out:
            out.append(value)
    return out


def filter_clues(raw_clues: list, events: list[dict], expression_type: str) -> list[str]:
    valid = collect_valid_clue_keys(events)
    clues = []
    for clue in raw_clues or []:
        if isinstance(clue, str) and clue in valid and clue not in clues:
            clues.append(clue)
    return clues or fallback_clues(events, expression_type)


def event_date_place(event: dict) -> str:
    scene = (event.get("scene_description") or "").strip()
    parts = scene.split(";", 2)
    if len(parts) >= 2:
        return f"{parts[0]}，{parts[1]}"
    if parts and parts[0]:
        return parts[0]
    return event.get("session_id", "某次记录")


def short_phrase(text: str, limit: int = 34) -> str:
    value = " ".join(str(text or "").replace("\n", " ").split())
    value = value.strip(" ，。；;、")
    if len(value) <= limit:
        return value
    return value[:limit].rstrip(" ，。；;、") + "..."


def event_hint(event: dict) -> str:
    """Return a natural event anchor without explicit date/place wording."""
    for key in ("explicit_preferences", "implicit_preferences"):
        prefs = event.get(key) or []
        if prefs:
            pref = prefs[0]
            category = str(pref.get("category") or "")
            subcategory = str(pref.get("subcategory") or "").strip()
            content = pref.get("content") or pref.get("subcategory") or ""
            if content:
                bits = [bit.strip() for bit in str(content).split(";") if bit.strip()]
                if category.startswith("Relationship"):
                    relation = subcategory or (bits[0] if bits else "关系人物")
                    name = bits[1] if len(bits) > 1 else ""
                    label = f"{relation}{name}" if name and name not in relation else relation
                    return f"和{label}互动的那次分享"
                if category.startswith("BasicPets"):
                    pet_name = bits[0] if bits else "宠物"
                    return f"和宠物{pet_name}相处的那次分享"
                return f"围绕“{short_phrase(content)}”展开的那次分享"

    scene = (event.get("scene_description") or "").strip()
    parts = scene.split(";", 2)
    detail = parts[2] if len(parts) >= 3 else scene
    first_sentence = detail.split("。", 1)[0]
    return f"那次关于“{short_phrase(first_sentence)}”的分享"


def pick_other_event(formatted_profile: dict, matched_events: list[dict]) -> dict | None:
    matched_ids = {e.get("session_id") for e in matched_events}
    for event in formatted_profile.get("events", []) or []:
        if event.get("session_id") not in matched_ids:
            return event
    return None


def event_text(event: dict) -> str:
    parts = [
        event.get("scene_description") or "",
        event.get("user_shared_image_description") or "",
        event.get("background_audio_info") or "",
        event.get("human_speech_content") or "",
    ]
    for turn in event.get("dialog_list", []) or []:
        parts.append(str(turn.get("user", "")))
        parts.append(str(turn.get("assistant", "")))
    return "\n".join(parts)


def compact_event_summary(event: dict) -> str:
    scene = event.get("scene_description") or ""
    parts = scene.split(";", 2)
    scene_body = parts[2] if len(parts) >= 3 else scene
    lines = []
    if scene_body:
        lines.append(f"场景/事件: {short_phrase(scene_body, 160)}")
    image = event.get("user_shared_image_description")
    if image and image != "none":
        lines.append(f"图像: {short_phrase(image, 120)}")
    audio = event.get("background_audio_info")
    if audio and audio != "none":
        lines.append(f"背景音: {short_phrase(audio, 120)}")
    speech = event.get("human_speech_content")
    if speech and speech != "none":
        lines.append(f"人声: {short_phrase(speech, 100)}")

    turns = []
    for turn in event.get("dialog_list", []) or []:
        user = str(turn.get("user", "")).strip()
        assistant = str(turn.get("assistant", "")).strip()
        if user:
            turns.append(f"用户: {short_phrase(user, 70)}")
        if assistant:
            turns.append(f"助手: {short_phrase(assistant, 70)}")
        if len(turns) >= 4:
            break
    if turns:
        lines.append("对话片段: " + " / ".join(turns))
    return "\n".join(lines)


def evidence_summary(events: list[dict], limit: int = 2) -> str:
    if not events:
        return "无"
    chunks = []
    for idx, event in enumerate(events[:limit], start=1):
        chunks.append(f"[证据{idx}]\n{compact_event_summary(event)}")
    return "\n\n".join(chunks)


def normalize_payload(data: dict, target_type: str) -> dict:
    raw_options = data.get("options") or {}
    options = {}
    for label in OPTION_LABELS:
        val = raw_options.get(label)
        if isinstance(val, str) and val.strip():
            options[label] = val.strip()

    return {
        "adversarial_type": str(data.get("adversarial_type") or target_type).strip(),
        "Q": str(data.get("Q") or data.get("question") or "").strip(),
        "options": options if sorted(options) == OPTION_LABELS else {},
        "A": str(data.get("A") or "").strip(),
        "adversarial_answer": str(data.get("adversarial_answer") or "").strip(),
        "trap_reason": str(data.get("trap_reason") or data.get("rationale") or "").strip(),
        "reasonable_answer": str(data.get("reasonable_answer") or "").strip(),
    }


def payload_is_valid(payload: dict, target_type: str, relationship_wrong_name: str | None) -> bool:
    q = payload.get("Q", "")
    if payload.get("adversarial_type") != target_type:
        return False
    if not q or not payload.get("trap_reason") or not payload.get("reasonable_answer"):
        return False
    if any(marker in q for marker in ["这段记录", "memory clue", "session", "回想某次分享"]):
        return False
    if re.search(r"\d{2}/\d{2}/\d{4}", q):
        return False
    if target_type == "person_owner_swap":
        if not (relationship_wrong_name and relationship_wrong_name in q):
            return False

    options = payload.get("options", {})
    answer = payload.get("A", "")
    adv_ans = payload.get("adversarial_answer", "")
    if options:
        if sorted(options) != OPTION_LABELS:
            return False
        refusal_opts = [k for k, v in options.items() if v == REFUSAL_TEXT]
        if len(refusal_opts) != 1:
            return False
        if answer and answer != refusal_opts[0]:
            return False
        if adv_ans and adv_ans not in options.values():
            return False
    return True


def pick_relationship_swap_name(
    profile: dict,
    item: dict,
    matched_events: list[dict],
) -> str | None:
    """Pick a wrong subject only from the current user's Relationship list.

    In this benchmark, subject-swap adversarial questions should not swap
    between different benchmark characters.  Prefer a relationship person who
    is absent from the lure events so the mismatch stays clean.
    """
    names = relationship_names(profile)
    if not names:
        return None

    event_blob = "\n".join(event_text(event) for event in matched_events)
    absent_names = [name for name in names if name not in event_blob]
    candidates = absent_names or names
    idx = (item["p_id"] + item["pref_idx"] + CATEGORIES.index(item["category"])) % len(candidates)
    return candidates[idx]


def subject_tail(question: str, subcategory: str) -> str:
    q = (question or "").strip()
    prefixes = [
        "该用户",
        "这位用户",
        "用户",
        "此用户",
    ]
    for prefix in prefixes:
        if q.startswith(prefix):
            tail = q[len(prefix):].lstrip()
            return tail or f"在{subcategory}方面更符合哪一项？"
    if subcategory:
        return f"在“{subcategory}”方面更符合哪一项？"
    return "更符合哪一项？"


def context_phrase(event: dict) -> str:
    for key in ("explicit_preferences", "implicit_preferences"):
        prefs = event.get(key) or []
        if not prefs:
            continue
        pref = prefs[0]
        category = str(pref.get("category") or "")
        subcategory = str(pref.get("subcategory") or "").strip()
        content = pref.get("content") or subcategory or ""
        bits = [bit.strip() for bit in str(content).split(";") if bit.strip()]
        if category.startswith("Relationship"):
            relation = subcategory or (bits[0] if bits else "关系人物")
            name = bits[1] if len(bits) > 1 else ""
            label = f"{relation}{name}" if name and name not in relation else relation
            return f"和{label}互动时"
        if category.startswith("BasicPets"):
            pet_name = bits[0] if bits else "宠物"
            return f"和宠物{pet_name}相处时"
        if content:
            return f"聊到“{short_phrase(content, 24)}”时"
    return "那次日常分享里"


def false_object_for_category(category: str, subcategory: str) -> str:
    key = f"{category}:{subcategory}"
    specific = {
        "FoodAndDrink:外食偏好": "连锁餐厅",
        "FoodAndDrink:咖啡与茶": "外带奶茶",
        "FoodAndDrink:烹饪习惯": "外卖安排",
        "FoodAndDrink:饮食风格": "戒饮品习惯",
        "HomeAndSpace:书架与收藏": "香氛展示角",
        "HomeAndSpace:整洁与收纳": "囤物方式",
        "HomeAndSpace:香氛与氛围": "强刺激香味",
        "HomeAndSpace:植物与绿植": "大型花园",
        "BodyAndHealth:睡眠习惯": "早睡计划",
        "BodyAndHealth:晨间习惯": "夜间仪式",
        "BodyAndHealth:运动方式": "高强度训练",
        "HobbiesAndEntertainment:阅读": "悬疑小说",
        "HobbiesAndEntertainment:影视与追剧": "悬疑剧",
        "HobbiesAndEntertainment:手工与创作": "纯数字工具",
        "HobbiesAndEntertainment:户外与自然": "竞技运动",
        "HobbiesAndEntertainment:乐器与音乐": "无结构噪音乐",
        "WorkAndLearning:职业特征": "朝九晚五办公室",
        "WorkAndLearning:工作专注度": "频繁社交打断",
        "WorkAndLearning:工作环境": "封闭无窗工位",
        "WorkAndLearning:学习方式": "速成培训课",
        "MobilityAndTravel:旅行偏好": "地标打卡路线",
        "MobilityAndTravel:旅行风格": "详细攻略行程",
        "MobilityAndTravel:日常通勤": "固定班车通勤",
        "Pets:宠物种类": "狗",
        "Pets:宠物用品": "华而不实的大型宠物用品",
    }
    generic = {
        "FoodAndDrink": "饮食选择",
        "HomeAndSpace": "居家安排",
        "BodyAndHealth": "健康计划",
        "HobbiesAndEntertainment": "娱乐内容",
        "WorkAndLearning": "工作学习方式",
        "MobilityAndTravel": "出行方式",
        "Pets": "宠物安排",
    }
    return specific.get(key) or generic.get(category, subcategory or "相关事项")


def loaded_concept_for_category(category: str, subcategory: str) -> str:
    key = f"{category}:{subcategory}"
    specific = {
        "FoodAndDrink:外食偏好": "网红打卡店",
        "FoodAndDrink:咖啡与茶": "咖啡依赖",
        "FoodAndDrink:烹饪习惯": "拒绝外食",
        "FoodAndDrink:饮食风格": "饮品执念",
        "HomeAndSpace:书架与收藏": "囤书癖",
        "HomeAndSpace:整洁与收纳": "洁癖",
        "HomeAndSpace:香氛与氛围": "气氛过度包装",
        "HomeAndSpace:植物与绿植": "植物控",
        "BodyAndHealth:睡眠习惯": "熬夜成瘾",
        "BodyAndHealth:晨间习惯": "仪式感强迫",
        "BodyAndHealth:运动方式": "健身执念",
        "HobbiesAndEntertainment:阅读": "消遣读物",
        "HobbiesAndEntertainment:影视与追剧": "肥皂剧",
        "HobbiesAndEntertainment:手工与创作": "低效手工",
        "HobbiesAndEntertainment:户外与自然": "漫无目的闲逛",
        "HobbiesAndEntertainment:乐器与音乐": "噪音偏好",
        "WorkAndLearning:职业特征": "逃避上班",
        "WorkAndLearning:工作专注度": "工作上头",
        "WorkAndLearning:工作环境": "挑剔工位",
        "WorkAndLearning:学习方式": "死读书",
        "MobilityAndTravel:旅行偏好": "盲目打卡",
        "MobilityAndTravel:旅行风格": "拒绝规划",
        "MobilityAndTravel:日常通勤": "通勤执念",
        "Pets:宠物种类": "宠物负担",
        "Pets:宠物用品": "宠物消费冲动",
    }
    return specific.get(key) or f"所谓的{false_object_for_category(category, subcategory)}"


def false_presupposition_context(category: str, subcategory: str) -> str:
    mapping = {
        "FoodAndDrink": "开设自己的生活方式餐厅时",
        "HomeAndSpace": "准备做家居改造节目时",
        "BodyAndHealth": "制定公开打卡训练计划时",
        "HobbiesAndEntertainment": "组织兴趣社群分享会时",
        "WorkAndLearning": "参加公司全职入职培训时",
        "MobilityAndTravel": "带旅行团做固定线路讲解时",
        "Pets": "参加宠物比赛时",
    }
    return mapping.get(category, f"公开介绍自己的{subcategory}计划时")


def adversarial_type_for_item(item: dict, has_relationship: bool) -> str:
    if item["expression_type"] == "implicit":
        types = [
            "implicit_overclaim",
            "person_owner_swap",
            "category_type_swap",
            "lexical_concept_swap",
            "polarity_flip",
            "false_presupposition",
            "event_context_swap",
            "attribute_slot_swap",
        ]
    else:
        types = [
            "person_owner_swap",
            "attribute_slot_swap",
            "category_type_swap",
            "lexical_concept_swap",
            "polarity_flip",
            "false_presupposition",
            "event_context_swap",
        ]
    selector = (item["p_id"] + item["pref_idx"] + CATEGORIES.index(item["category"])) % len(types)
    adv_type = types[selector]
    if adv_type == "person_owner_swap" and not has_relationship:
        return "attribute_slot_swap"
    return adv_type


def pick_balanced_adversarial_types(
    p_id: int,
    has_relationship: bool,
    expression_type: str,
    counters: dict[int, dict[str, int]],
    n: int = QAS_PER_PREF,
) -> list[str]:
    """Pick *n* distinct adversarial types, balancing per-person distribution.

    For each pick, choose the type with the lowest count for this person,
    breaking ties by the canonical order in ADVERSARIAL_TYPES.
    """
    if expression_type == "implicit":
        candidates = list(ADVERSARIAL_TYPES)
    else:
        candidates = [t for t in ADVERSARIAL_TYPES if t != "implicit_overclaim"]

    if not has_relationship:
        candidates = [t for t in candidates if t != "person_owner_swap"]

    person_counts = counters.setdefault(p_id, {t: 0 for t in ADVERSARIAL_TYPES})

    picked: list[str] = []
    for _ in range(n):
        available = [t for t in candidates if t not in picked]
        if not available:
            available = list(candidates)
        available.sort(key=lambda t: (person_counts[t], ADVERSARIAL_TYPES.index(t)))
        choice = available[0]
        picked.append(choice)
        person_counts[choice] += 1

    return picked


def _fallback_options(
    adv_answer: str, distractor1: str, distractor2: str, refusal_slot: int,
) -> tuple[dict, str]:
    ordered = [None] * 4
    ordered[refusal_slot] = REFUSAL_TEXT
    remaining = [i for i in range(4) if i != refusal_slot]
    ordered[remaining[0]] = adv_answer
    ordered[remaining[1]] = distractor1
    ordered[remaining[2]] = distractor2
    options = {label: ordered[idx] for idx, label in enumerate(OPTION_LABELS)}
    return options, OPTION_LABELS[refusal_slot]


def build_question_payload_fallback(
    base_question: str,
    item: dict,
    true_name: str,
    relationship_wrong_name: str | None,
    matched_events: list[dict],
    formatted_profile: dict,
    target_type: str,
    base_options: dict,
    base_answer: str,
    refusal_slot: int,
) -> dict:
    tail = subject_tail(base_question, item["subcategory"])
    category = item["category"]
    subcategory = item["subcategory"]
    wrong_object = false_object_for_category(category, subcategory)
    loaded = loaded_concept_for_category(category, subcategory)
    adv_type = target_type
    true_pref = item["preference"]

    base_adv_answer = str(base_options.get(base_answer, "")).strip()
    base_distractors = [
        str(base_options[l]).strip()
        for l in OPTION_LABELS
        if l != base_answer and str(base_options.get(l, "")).strip()
    ]
    while len(base_distractors) < 2:
        base_distractors.append("同领域但历史未支持的另一选项")

    payload: dict = {
        "adversarial_type": adv_type,
        "Q": "",
        "options": {},
        "A": "",
        "adversarial_answer": "",
        "trap_reason": "",
        "reasonable_answer": "",
    }

    if adv_type == "person_owner_swap":
        payload["Q"] = f"{relationship_wrong_name}{tail}"
        opts, ans = _fallback_options(base_adv_answer, base_distractors[0], base_distractors[1], refusal_slot)
        payload["options"] = opts
        payload["A"] = ans
        payload["adversarial_answer"] = base_adv_answer
        payload["trap_reason"] = (
            f"真实诱饵偏好属于{true_name}，题干把偏好归到了关系人物{relationship_wrong_name}身上。"
        )
        payload["reasonable_answer"] = (
            f"历史中没有说明{relationship_wrong_name}{tail.rstrip('？?')}；"
            f"只知道{true_name}的相关偏好是：{true_pref}。"
        )
        return payload

    if adv_type == "attribute_slot_swap":
        payload["Q"] = f"{true_name}提到的{wrong_object}最符合哪一项？"
        opts, ans = _fallback_options(
            f"偏好与{subcategory}类似的{wrong_object}",
            f"对{wrong_object}非常讲究",
            f"对{wrong_object}没有明显倾向",
            refusal_slot,
        )
        payload["options"] = opts
        payload["A"] = ans
        payload["adversarial_answer"] = f"偏好与{subcategory}类似的{wrong_object}"
        payload["trap_reason"] = (
            f"真实信息支持的是“{subcategory}”下的偏好，题干把对象槽位改成了“{wrong_object}”。"
        )
        payload["reasonable_answer"] = (
            f"历史中没有可靠信息说明{true_name}提到过{wrong_object}；"
            f"可支持的偏好是：{true_pref}。"
        )
        return payload

    if adv_type == "category_type_swap":
        payload["Q"] = f"{true_name}在{wrong_object}方面更偏向哪一项？"
        opts, ans = _fallback_options(
            f"在{wrong_object}方面有自己的固定偏好",
            f"对{wrong_object}比较随性",
            f"在{wrong_object}方面跟随主流",
            refusal_slot,
        )
        payload["options"] = opts
        payload["A"] = ans
        payload["adversarial_answer"] = f"在{wrong_object}方面有自己的固定偏好"
        payload["trap_reason"] = (
            f"诱饵答案来自{subcategory}偏好，题干却换成了“{wrong_object}”这一不匹配类别。"
        )
        payload["reasonable_answer"] = (
            f"历史中没有说明{true_name}在{wrong_object}方面的偏好；"
            f"相关证据只支持：{true_pref}。"
        )
        return payload

    if adv_type == "lexical_concept_swap":
        payload["Q"] = f"{true_name}所谓的“{loaded}”具体指什么？"
        opts, ans = _fallback_options(base_adv_answer, base_distractors[0], base_distractors[1], refusal_slot)
        payload["options"] = opts
        payload["A"] = ans
        payload["adversarial_answer"] = base_adv_answer
        payload["trap_reason"] = (
            f"题干把中性的偏好概念恶意改写成“{loaded}”，原始记忆并没有这个说法。"
        )
        payload["reasonable_answer"] = (
            f"历史中没有把{true_name}的偏好称为“{loaded}”；"
            f"更准确的说法是：{true_pref}。"
        )
        return payload

    if adv_type == "polarity_flip":
        payload["Q"] = f"{true_name}在{subcategory}方面最排斥哪一项？"
        opts, ans = _fallback_options(base_adv_answer, base_distractors[0], base_distractors[1], refusal_slot)
        payload["options"] = opts
        payload["A"] = ans
        payload["adversarial_answer"] = base_adv_answer
        payload["trap_reason"] = (
            "题干把正向偏好改成了负向排斥，容易诱导模型把喜欢的内容当成不喜欢的内容。"
        )
        payload["reasonable_answer"] = (
            f"历史中没有说明{true_name}最排斥哪类{subcategory}；"
            f"相反，证据支持她/他偏向：{true_pref}。"
        )
        return payload

    if adv_type == "false_presupposition":
        false_context = false_presupposition_context(category, subcategory)
        payload["Q"] = f"{true_name}{false_context}，最强调哪一项？"
        opts, ans = _fallback_options(base_adv_answer, base_distractors[0], base_distractors[1], refusal_slot)
        payload["options"] = opts
        payload["A"] = ans
        payload["adversarial_answer"] = base_adv_answer
        payload["trap_reason"] = (
            f"题干强行假设“{false_context}”发生过，但历史没有这个事件前提。"
        )
        payload["reasonable_answer"] = (
            f"历史中没有说明{true_name}{false_context}；"
            f"只能确认相关偏好是：{true_pref}。"
        )
        return payload

    if adv_type == "event_context_swap":
        other_event = pick_other_event(formatted_profile, matched_events)
        if other_event:
            context = context_phrase(other_event)
        else:
            context = "聊到另一个日常话题时"
        payload["Q"] = f"{true_name}{context}，{tail}"
        opts, ans = _fallback_options(base_adv_answer, base_distractors[0], base_distractors[1], refusal_slot)
        payload["options"] = opts
        payload["A"] = ans
        payload["adversarial_answer"] = base_adv_answer
        payload["trap_reason"] = (
            "诱饵答案来自另一个真实偏好证据，题干把它塞进了不匹配的事件语境。"
        )
        payload["reasonable_answer"] = (
            f"历史中没有说明{true_name}{context}{tail.rstrip('？?')}；"
            f"诱饵答案只可支持原偏好：{true_pref}。"
        )
        return payload

    payload["adversarial_type"] = "implicit_overclaim"
    payload["Q"] = f"{true_name}在对话里明确说过的“{subcategory}”习惯是哪一项？"
    adapted_adv = f"有意识地保持{subcategory}习惯"
    opts, ans = _fallback_options(
        adapted_adv,
        f"偶尔提到过{subcategory}相关话题",
        f"从未关注过{subcategory}方面",
        refusal_slot,
    )
    payload["options"] = opts
    payload["A"] = ans
    payload["adversarial_answer"] = adapted_adv
    payload["trap_reason"] = (
        "真实诱饵来自隐式线索（如背景音或图像边缘），题干却要求它是对话中明确说出的信息。"
    )
    payload["reasonable_answer"] = (
        f"历史中没有说明{true_name}在对话里明确说过这一点；"
        f"只能从隐式线索推测：{true_pref}。"
    )
    return payload


def build_question_payload(
    base_question: str,
    base_options: dict,
    item: dict,
    true_name: str,
    relationship_wrong_name: str | None,
    matched_events: list[dict],
    formatted_profile: dict,
    base_answer: str,
    refusal_slot: int,
    target_type: str,
) -> tuple[dict, int, int]:
    base_adversarial_answer = str(base_options.get(base_answer, "")).strip()
    other_event = pick_other_event(formatted_profile, matched_events)
    wrong_context = context_phrase(other_event) if other_event else "另一个不相关日常语境"
    relationship_candidates = relationship_wrong_name or "无"

    prompt = PROMPT_GEN_ADVERSARIAL.format(
        target_type=target_type,
        good_case=json.dumps(GOOD_CASES[target_type], ensure_ascii=False, indent=2),
        true_name=true_name,
        relationship_candidates=relationship_candidates,
        relationship_wrong_name=relationship_wrong_name or "无",
        category=item["category"],
        subcategory=item["subcategory"],
        preference=item["preference"],
        expression_type=item["expression_type"],
        evidence_sources=", ".join(item["evidence_sources"])
        if isinstance(item["evidence_sources"], list)
        else str(item["evidence_sources"]),
        analysis="\n".join(f"- {x}" for x in item["analysis"])
        if isinstance(item["analysis"], list)
        else str(item["analysis"]),
        base_question=base_question,
        adversarial_answer=base_adversarial_answer,
        base_options=json.dumps(base_options, ensure_ascii=False),
        evidence_summary=evidence_summary(matched_events),
        wrong_context=wrong_context,
    )

    fallback = build_question_payload_fallback(
        base_question,
        item,
        true_name,
        relationship_wrong_name,
        matched_events,
        formatted_profile,
        target_type,
        base_options,
        base_answer,
        refusal_slot,
    )

    try:
        data, tokens_in, tokens_out = call_llm(prompt, temperature=TEMPERATURE_GEN)
        payload = normalize_payload(data, target_type)
        if payload_is_valid(payload, target_type, relationship_wrong_name):
            payload["llm_generated"] = True
            return payload, tokens_in, tokens_out
        print(f"[{item['p_id']}-{item['pref_code']}] invalid LLM payload, fallback: {payload}")
    except Exception as exc:
        print(f"[{item['p_id']}-{item['pref_code']}] LLM generation failed, fallback: {exc}")

    fallback["llm_generated"] = False
    return fallback, 0, 0


def validate_record(record: dict, matched_events: list[dict]) -> None:
    required = [
        "qa_id",
        "p_id",
        "category",
        "subcategory",
        "preference",
        "expression_type",
        "evidence_sources",
        "adversarial_type",
        "Q",
        "options",
        "A",
        "adversarial_answer",
        "memory clue",
        "matched_session_ids",
        "rationale",
        "type",
    ]
    missing = [key for key in required if key not in record]
    if missing:
        raise ValueError(f"{record.get('qa_id', '<unknown>')} missing fields: {missing}")

    options = record["options"]
    if sorted(options) != OPTION_LABELS:
        raise ValueError(f"{record['qa_id']} must have A/B/C/D options")
    refusal_letters = [k for k, v in options.items() if v == REFUSAL_TEXT]
    if refusal_letters != [record["A"]]:
        raise ValueError(f"{record['qa_id']} must have exactly one refusal answer")
    if record["A"] not in OPTION_LABELS:
        raise ValueError(f"{record['qa_id']} has invalid answer letter")
    if record["adversarial_answer"] not in options.values():
        raise ValueError(f"{record['qa_id']} adversarial_answer must appear in options")

    valid = collect_valid_clue_keys(matched_events)
    bad_clues = [c for c in record["memory clue"] if c not in valid]
    if bad_clues:
        raise ValueError(f"{record['qa_id']} invalid memory clues: {bad_clues}")


def build_records(
    sample: int | None = None,
    workers: int = DEFAULT_WORKERS,
    only_profile_ids: set[int] | None = None,
    skip_existing_qa_ids: set[str] | None = None,
) -> list[dict]:
    print("Loading data files...")
    profiles = load_json_or_jsonl(PROFILE_PATH)
    formatted_profiles = load_json_or_jsonl(FORMATTED_DIALOG_PATH)
    preference_qas = load_json_or_jsonl(PREFERENCE_QA_PATH)
    print(f"Loaded {len(profiles)} profiles, {len(formatted_profiles)} formatted, {len(preference_qas)} preference QAs")
    print(f"Generating {QAS_PER_PREF} QAs per preference with balanced adversarial types (workers={workers})\n")
    if only_profile_ids is not None:
        print(f"Only processing p_id(s): {sorted(only_profile_ids)}")
    skip_existing_qa_ids = skip_existing_qa_ids or set()
    if skip_existing_qa_ids:
        print(f"Resume: skipping {len(skip_existing_qa_ids)} existing qa_id(s).")

    formatted_by_pid = {int(p.get("p_id", idx)): p for idx, p in enumerate(formatted_profiles)}
    preference_qa_by_id = {q.get("qa_id"): q for q in preference_qas if q.get("qa_id")}
    type_counters: dict[int, dict[str, int]] = {}

    tasks: list[dict] = []
    for profile in profiles:
        p_id = int(profile.get("id", 0))
        if only_profile_ids is not None and p_id not in only_profile_ids:
            continue
        formatted_profile = formatted_by_pid.get(p_id, {})
        true_name = profile_name(profile)
        has_relationship = bool(relationship_names(profile))

        for item in preference_items(profile):
            qa_id_base = f"{p_id}-{item['category']}-{item['pref_idx']}"
            base_qa = preference_qa_by_id.get(qa_id_base)
            if not base_qa:
                continue

            matched_events = collect_preference_events(formatted_profile, item["pref_code"])
            if not matched_events:
                continue

            relationship_wrong_name = pick_relationship_swap_name(profile, item, matched_events)
            memory_clue = filter_clues(
                base_qa.get("memory clue", []),
                matched_events,
                item["expression_type"],
            )
            matched_session_ids = sorted(
                {e.get("session_id", "") for e in matched_events if e.get("session_id")}
            )

            adv_types = pick_balanced_adversarial_types(
                p_id, has_relationship, item["expression_type"],
                type_counters, n=QAS_PER_PREF,
            )

            for qi, target_type in enumerate(adv_types):
                qa_id = f"{qa_id_base}-adv{qi}"
                if qa_id in skip_existing_qa_ids:
                    continue
                tasks.append({
                    "qa_id": qa_id,
                    "qi": qi,
                    "item": item,
                    "base_qa": base_qa,
                    "true_name": true_name,
                    "relationship_wrong_name": relationship_wrong_name,
                    "matched_events": matched_events,
                    "formatted_profile": formatted_profile,
                    "memory_clue": memory_clue,
                    "matched_session_ids": matched_session_ids,
                    "target_type": target_type,
                    "refusal_slot": (p_id + item["pref_idx"] + CATEGORIES.index(item["category"]) + qi) % 4,
                })
                if sample is not None and len(tasks) >= sample:
                    break
            if sample is not None and len(tasks) >= sample:
                break
        if sample is not None and len(tasks) >= sample:
            break

    total = len(tasks)
    print(f"Collected {total} tasks, launching with {workers} workers...\n")

    print_lock = threading.Lock()
    done_counter = [0]

    def process_task(task: dict) -> dict:
        qa_id = task["qa_id"]
        target_type = task["target_type"]
        item = task["item"]
        base_qa = task["base_qa"]

        question_payload, tokens_in, tokens_out = build_question_payload(
            base_qa.get("Q", ""),
            base_qa.get("options", {}),
            item,
            task["true_name"],
            task["relationship_wrong_name"],
            task["matched_events"],
            task["formatted_profile"],
            base_qa.get("A", ""),
            task["refusal_slot"],
            target_type,
        )

        record = {
            "qa_id": qa_id,
            "p_id": item["p_id"],
            "category": item["category"],
            "subcategory": item["subcategory"],
            "preference": item["preference"],
            "expression_type": item["expression_type"],
            "evidence_sources": item["evidence_sources"],
            "adversarial_type": question_payload["adversarial_type"],
            "Q": question_payload["Q"],
            "options": question_payload["options"],
            "A": question_payload["A"],
            "adversarial_answer": question_payload["adversarial_answer"],
            "memory clue": task["memory_clue"],
            "matched_session_ids": task["matched_session_ids"],
            "trap_reason": question_payload["trap_reason"],
            "reasonable_answer": question_payload["reasonable_answer"],
            "rationale": question_payload["trap_reason"],
            "llm_generated": question_payload.get("llm_generated", False),
            "tokens_in": tokens_in,
            "tokens_out": tokens_out,
            "type": "adversarial_mcq",
        }
        validate_record(record, task["matched_events"])

        with print_lock:
            done_counter[0] += 1
            print(f"[{done_counter[0]}/{total}] {qa_id} ({target_type}) "
                  f"llm={question_payload.get('llm_generated')} in={tokens_in} out={tokens_out}")

        return record

    if workers <= 1:
        records = [process_task(t) for t in tasks]
    else:
        records = []
        with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
            futures = {executor.submit(process_task, t): t for t in tasks}
            for future in concurrent.futures.as_completed(futures):
                try:
                    records.append(future.result())
                except Exception as exc:
                    task = futures[future]
                    print(f"[ERROR] {task['qa_id']}: {exc}")

    records.sort(
        key=lambda r: (
            r["p_id"],
            CATEGORIES.index(r["category"]) if r["category"] in CATEGORIES else 99,
            r["qa_id"],
        )
    )
    return records


def load_existing_output(path: Path) -> dict[str, dict]:
    """Load existing adversarial QA output as {qa_id: record}."""
    if not path.exists():
        return {}
    try:
        records = load_json_or_jsonl(path)
    except Exception as exc:
        print(f"WARN: failed to load existing output {path}: {exc}")
        return {}
    existing: dict[str, dict] = {}
    for record in records:
        qa_id = record.get("qa_id")
        if qa_id:
            existing[str(qa_id)] = record
    return existing


def sort_records(records: list[dict]) -> list[dict]:
    return sorted(
        records,
        key=lambda r: (
            int(r.get("p_id", 10**9)),
            CATEGORIES.index(r.get("category", "")) if r.get("category") in CATEGORIES else 99,
            str(r.get("qa_id", "")),
        ),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate LLM adversarial preference MCQs.")
    parser.add_argument(
        "--sample",
        type=int,
        default=None,
        metavar="N",
        help="Stop after generating N QA records (default: generate all).",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=DEFAULT_WORKERS,
        metavar="W",
        help=f"Number of concurrent LLM workers (default: {DEFAULT_WORKERS}). Set to 1 for serial execution.",
    )
    parser.add_argument(
        "--only_profile_ids",
        "--only-profile-ids",
        type=str,
        default=None,
        help="Comma/space separated p_id list to process, e.g. 5,6,7. Unselected existing records are preserved.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Load existing output, skip existing qa_id(s), and merge newly generated records back.",
    )
    args = parser.parse_args()

    only_profile_ids = parse_profile_ids(args.only_profile_ids)
    existing_map = load_existing_output(OUTPUT_PATH) if (args.resume or only_profile_ids is not None) else {}
    if existing_map:
        print(f"Loaded existing output: {len(existing_map)} records from {OUTPUT_PATH}")

    skip_existing = set(existing_map) if args.resume else set()
    generated_records = build_records(
        sample=args.sample,
        workers=args.workers,
        only_profile_ids=only_profile_ids,
        skip_existing_qa_ids=skip_existing,
    )

    if args.resume or only_profile_ids is not None:
        qa_map = dict(existing_map)
        if only_profile_ids is not None and not args.resume:
            qa_map = {
                qa_id: record
                for qa_id, record in qa_map.items()
                if int(record.get("p_id", -1)) not in only_profile_ids
            }
        for record in generated_records:
            qa_map[record["qa_id"]] = record
        records = sort_records(list(qa_map.values()))
    else:
        records = generated_records

    tmp_path = OUTPUT_PATH.with_suffix(OUTPUT_PATH.suffix + ".tmp")
    os.makedirs(OUTPUT_PATH.parent, exist_ok=True)
    tmp_path.write_text(json.dumps(records, ensure_ascii=False, indent=4), encoding="utf-8")
    os.replace(tmp_path, OUTPUT_PATH)

    by_expression: dict[str, int] = {}
    by_type: dict[str, int] = {}
    by_person_type: dict[int, dict[str, int]] = {}
    for record in records:
        by_expression[record["expression_type"]] = by_expression.get(record["expression_type"], 0) + 1
        by_type[record["adversarial_type"]] = by_type.get(record["adversarial_type"], 0) + 1
        pid = record["p_id"]
        pt = by_person_type.setdefault(pid, {})
        pt[record["adversarial_type"]] = pt.get(record["adversarial_type"], 0) + 1

    print(f"\nWrote {len(records)} records to {OUTPUT_PATH}")
    print(f"Generated this run: {len(generated_records)}")
    if existing_map:
        print(f"Preserved/merged existing records: {len(existing_map)}")
    print(f"By expression_type: {by_expression}")
    print(f"By adversarial_type: {by_type}")
    print("\nPer-person adversarial type distribution:")
    for pid in sorted(by_person_type):
        counts = by_person_type[pid]
        dist = ", ".join(f"{t}: {counts.get(t, 0)}" for t in ADVERSARIAL_TYPES)
        print(f"  p_id {pid} (total {sum(counts.values())}): {dist}")


if __name__ == "__main__":
    main()
